'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});

var _constants = require('../../utils/constants');

var options = JSON.parse(localStorage.getItem(_constants.OPTIONS_LS_KEY)) || {};

exports.default = '\n\n  .olyauth__centralizer{\n    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; \n    font-weight: 300;\n  }\n   \n\t.olyauth__centralizerGravatar:hover,\n\t.olyauth__centralizer button:hover,\n\t.olyauth__profileUploadInner input[type="file"]:hover,\n\t.olyauth__centralizerAppsIcon:hover:after{\n\t\tcursor: pointer !important;\n\t\topacity: 0.7;\n  }\n  .olyauth__centralizerGravatar--cssGravatar{\n    display: table;\n  }\n  .olyauth__centralizerGravatar--cssGravatar p{\n    color: #fff;\n    width: 100%;\n    height: 100%;\n    border-radius: 50%;\n    margin: 0;\n    font-size: 16px;\n    text-align: center;\n    font-weight: 100;\n    line-height: 100%;\n    display: table-cell;\n    vertical-align: middle;\n  }\n\n\t.olyauth__mainMenuInner ul li:hover{\n\t\tbackground: #f7f7f7;\n\t\tcolor: #333;\n\t\tcursor: pointer;\n\t\tborder-radius: 3px;\n\t}\n\n\t.olyauth__centralizerAppsIcon:after{\n\t\tcontent:"\\f00a";\n\t\tfont-family:FontAwesome;\n\t\tcolor: ' + (options.centralizerAppsIconColor || '#efefef') + '; \n\t\tposition: absolute;\n\t\twidth: 45px;\n\t\theight: 45px;\n\t\tfont-size: 18px;\n\t}\n\n\t.top_arr:after, .top_arr:before {\n\t\tbottom: 100%;\n\t\tright: 4px;\n\t\tborder: solid transparent;\n\t\tcontent: " ";\n\t\theight: 0;\n\t\twidth: 0;\n\t\tposition: absolute;\n\t\tpointer-events: none;\n\t}\n\n\t.top_arr:before {\n\t\tborder-color: rgba(222, 221, 223, 0);\n\t\tborder-bottom-color: #fff;\n\t\tborder-width: 13px;\n\t\tmargin-left: -13px;\n\t}\n\n\t.top_arr:after{\n\t\tborder-color: rgba(222, 221, 223, 0);\n\t\tborder-bottom-color: #fff;\n\t\tborder-width: 13px;\n\t\tmargin-left: -13px;\n\t}\n\n\t.olyauth__centralizerAppContainer.top_arr:before,\n\t.olyauth__centralizerAppContainer.top_arr:after{\n\t\tright: 43px;\n\t}\n\n\n';